// One-shot helper for the GameScene audio extraction: rewrites this.<x> to this.audio.<x>
import fs from 'node:fs';

const methods = ['ensureSharedAudioContext','connectGameAudio','stopOscillator','playMerasmusFlipSound','startMerasmusHum','stopMerasmusHum','updateMerasmusHumVolume','playMerasmusCackle','playLureSound','playLurePlacedSound','playLureConsumedSound','playVictoryChime','play6AMBellChime','playGiveUpSound','playGoodEndingSound','playBadEndingIntroSound','playDarkEndingSound','startDemoEyeGlowSound','stopDemoEyeGlowSound','playJumpscareSound','playCameraSwitchSound','playHeavyFootsteps','playTeleportSound','playEnemyApproachSound','startApproachGrowl','updateApproachGrowl','stopApproachGrowl','playSniperChargeSound','playSniperTeleportSound','playPyroMatchSound','startPyroCracklingAmbient','schedulePyroCrackle','playPyroCrackleSound','stopPyroCracklingAmbient','createPyroHallwayNoiseBuffer','startPyroHallwayHiss','applyPyroHallwayHissAudible','applyPyroHallwayHissMuted','updatePyroHallwayHiss','disconnectPyroHallwayHissNodes','stopPyroHallwayHiss','updatePyroHallwayAudio','playPyroBurningSound','playPyroReflectSound','playUberChargeSound','playCameraWatchWarningSound','playDeniedSound','playSentryBuildSound','playSentryRepairSound','playSentryUpgradeSound','playWranglerAimSound','playEnemyRetreatSound','playWranglerToggleSound','playPauseSound','playUnpauseSound','playScreenFlipSound','playCameraBootSound','playCameraStaticBurst','playCameraDestroySound','playVentTabClickSound','playVentSealSound','playVentThudSound','playThermostatBeep','playCassetteStopSound','startSniperLaserHum','stopSniperLaserHum','startDispenserHum','stopDispenserHum','startIntelRoomAmbience','stopIntelRoomAmbience','disposeIntelRoomAmbience','playSapperSound','stopSapperSound','playAdministratorTargetingSound','playAdministratorHackSound','playAdministratorRepairTickSound','playAdministratorRepairCompleteSound','startDetectionSound','updateDetectionSoundIntensity','stopDetectionSound','stopAllGameSounds','playSound','playDemomanBattleCry','playDemomanDistantCry','playScoutLingerApproach','playMedicGhostScream','stopMedicGhostScream'];
const fields = ['demoEyeGlowSoundPlaying','demoEyeGlowOscillator','demoEyeGlowOscillator2','demoEyeGlowLfo','demoEyeGlowLfoGain','demoEyeGlowGain','medicGhostAudioContext','medicGhostOscillators','merasmusHumOscillator','merasmusHumOscillator2','merasmusHumGain','merasmusHumPlaying','sapperSoundOscillator','sapperSoundModulator','sapperSoundGain','isPlayingSapperSound','isPlayingDetectionSound','detectionSoundReleaseFrames','detectionOscillator','detectionGain','detectionLfo','detectionLfoGain','isPlayingSniperHum','sniperHumOscillator','sniperHumOscillator2','sniperHumGain','isPlayingPyroHallwayHiss','pyroHallwayHissStopping','pyroHallwayHissGain','pyroHallwayHissBodyNoise','pyroHallwayHissBodyFilter','pyroHallwayHissBodyGain','pyroHallwayHissHissNoise','pyroHallwayHissHissHighpass','pyroHallwayHissHissFilter','pyroHallwayHissHissGain','pyroHallwayHissPanner','pyroHallwayHissSide','pyroHallwayHissStopTimeout','pyroHallwayHissAudible','pyroHallwayHissIntroDone','sharedAudioContext','masterAudioGain','masterAudioCompressor','isPlayingDispenserHum','dispenserHumOscillator','dispenserHumOscillator2','dispenserHumLfo','dispenserHumSecondaryGain','dispenserHumGain','intelRoomAmbience','approachGrowlOsc','approachGrowlOsc2','approachGrowlGain','pyroCracklingGain','pyroCracklingInterval','pyroCracklingIntensity','pyroCracklingLastInterval','cameraWarningSoundPlaying','pyroBurningSoundThrottle','_administratorRepairSoundTimer'];

const f = 'src/scenes/GameScene.ts';
let t = fs.readFileSync(f, 'utf8');
let n = 0;
t = t.replace(new RegExp('this\\.(' + methods.join('|') + ')\\(', 'g'), (_m, name) => { n++; return 'this.audio.' + name + '('; });
let nf = 0;
t = t.replace(new RegExp('this\\.(' + fields.join('|') + ')\\b', 'g'), (_m, name) => { nf++; return 'this.audio.' + name; });
t = t.replace("import { setGameClock } from '../utils/gameClock';", "import { GameAudio } from '../audio/GameAudio';\nimport { setGameClock } from '../utils/gameClock';");
t = t.replace('export class GameScene extends Phaser.Scene {', 'export class GameScene extends Phaser.Scene {\n  private audio: GameAudio = new GameAudio(this);\n');
fs.writeFileSync(f, t);
console.log('method call rewrites:', n, '| field rewrites:', nf);
